import Navbar from "@/components/navbar";
import { Toaster } from "@/components/ui/toaster";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ProviderLayout from "./Provider";
import { ThemeProvider } from "@/components/themeprovider/theme-provider";
import ThemeSwitcher from "@/components/theme-switcher";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
 children,
}: Readonly<{ children: React.ReactNode }>) {
 return (
   <html lang="en" suppressHydrationWarning>
     <body suppressHydrationWarning className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
       <div className="min-h-screen pt-20 flex flex-col">
         <ProviderLayout>
           <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
             <Navbar />
             <ThemeSwitcher />
             {children}
           </ThemeProvider>
         </ProviderLayout>
       </div>
       <Toaster />
     </body>
   </html>
 );
}